Added effect "Displeased Denise"
gta-chaos-mod/ChaosModV pull request #1229
Opened 2021-04-30 02:54 UTC by ubscal

Spawns hostile version of Denise with a Gadget Pistol

2021-04-30 05:51 UTC, Last0xygen requested changes

2021-04-30 05:51 UTC, Last0xygen commented on ChaosMod/Effects/db/Peds/PedsSpawnAngryDenise.cpp
> +	Hash relationshipGroup;
I created a helper function for this, see PedsSpawnSpaceRanger.cpp

2021-06-04 17:31 UTC, ubscal commented
Thought i closed this a long time ago, closed for  being too similar to other effects

2021-06-04 17:31 UTC, closed without merging

2021-06-05 04:27 UTC, TheRealAyCe commented
Are you sure? With the effect groups this should be fine IMO. More variety sounds good.