new effect "Golf %"
gta-chaos-mod/ChaosModV pull request #162
Opened 2020-11-10 10:03 UTC by vladig98

Gives player a golf stick and removes all of his other weapons,
Sets player in a golf caddy
Dresses player in golf clothes

2020-11-10 10:09 UTC, Last0xygen requested changes

2020-11-10 10:09 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +	DELETE_VEHICLE(&toRemove);
The current vehicle should not be removed, as it leads to softlocks if the vehicle is a mission entity

2020-11-10 10:09 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +	else if (pedType == 3)
Trevor is 2, I thought

2020-11-10 10:09 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +	SET_PED_INTO_VEHICLE(playerPed, veh, -1);
You should sleep for (0) to ensure the vehicle spawned

2020-11-10 10:09 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +static void OnStop()
Remove if not needed

2020-11-10 10:09 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +static void OnTick()
Remove if not needed

2020-11-10 10:09 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +static RegisterEffect registerEffect(EFFECT_GOLF_PERCENT, OnStart, OnStop, OnTick);
Replace onStop and OnTick with nullptr

2020-11-10 13:53 UTC, vladig98 commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +	else if (pedType == 3)
Trevor is 3

2020-11-25 14:21 UTC, pongo1231 commented on ChaosMod/Effects/db/Player/GolfPercent.cpp
> +	Vehicle veh = CREATE_VEHICLE(caddyModel, playerPos.x, playerPos.y, playerPos.z, heading, true, true, true);
Use `CreateTempVehicle` here instead as otherwise it will stay on the map forever and won't despawn.

2020-11-25 14:23 UTC, pongo1231 commented
Also you should exclude your `ChaosMod.sln` from being commited since it's not related to the effect in any way.

2021-05-29 23:23 UTC, pongo1231 commented
Now your PR is trying to delete project files instead, make sure to completely exclude them from your PR instead of deleting them.

2024-04-20 19:54 UTC, closed without merging