Added Movement Speed Multiplier Effects
gta-chaos-mod/ChaosModV pull request #3037
Opened 2022-06-02 14:40 UTC by OnlyRealNubs

These consist of:
```
10x Movement Speed
5x Movement Speed
0.5x Movement Speed
```

2022-07-16 20:24 UTC, Last0xygen requested changes

2022-07-16 20:24 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerMovementSpeed.cpp
> +
missing clang on 😏

2023-01-19 17:08 UTC, pongo1231 commented
They're missing from the config app

2023-01-19 17:22 UTC, OnlyRealNubs commented
Fixed

2023-01-19 17:25 UTC, pongo1231 commented
5x Movement Speed and 10x Movement Speed are marked as short timed in the mod but not in the config app.

I'd probably just make both of them normal timed in the mod.

2023-01-19 17:27 UTC, OnlyRealNubs commented
Ahh. I read only 0.5 as short.  Fixed now.

2023-01-19 17:31 UTC, merged