Added effects "Detach Random Wheel" and "Disassemble Current Vehicle"
gta-chaos-mod/ChaosModV pull request #3064
Opened 2022-06-12 23:18 UTC by Reguas

& assets for entity fragments
![Screenshot from 2022-06-13 01-57-48](https://user-images.githubusercontent.com/64607261/173257640-9152c989-9410-4c7b-85cb-4a2d22647bfa.png)

2022-06-12 23:24 UTC, OnlyRealNubs commented
Looks nice! I envy the work you did here.

2022-06-12 23:25 UTC, Reguas commented
Well, most of it was copy-pasting the code from SHVDotNet source xD

2022-06-12 23:26 UTC, OnlyRealNubs commented
> Well, most of it was copy-pasting the code from SHVDotNet source xD

Well still, well done lol

2023-01-19 17:40 UTC, pongo1231 requested changes

2023-01-19 17:40 UTC, pongo1231 commented on ChaosMod/Effects/db/Vehs/VehsDetachWheel.cpp
> +#include <stdafx.h>
Should be the first include, add an empty line between both to make sure they don't get reordered by the formatter

```suggestion
#include <stdafx.h>

#include "Memory/EntityFragments.h"
```

2023-01-19 17:40 UTC, pongo1231 commented on ChaosMod/Effects/db/Vehs/VehsDetachWheel.cpp
> +);
Indents are missing here

2023-01-19 17:40 UTC, pongo1231 commented on ChaosMod/Effects/db/Vehs/VehsDisassemble.cpp
> +#include <stdafx.h>
Same applies here

2023-01-19 17:40 UTC, pongo1231 commented on ChaosMod/Effects/db/Vehs/VehsDisassemble.cpp
> +);
Here too

2023-01-23 20:57 UTC, merged