Added Effect: Animorph Player
gta-chaos-mod/ChaosModV pull request #526
Opened 2021-02-03 16:20 UTC by Chankaaa

Transforms the player into a random animal out of a pool of 24 possible animals.

2021-02-03 17:27 UTC, kolyaventuri commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +	Cleanup();
If nothing else is happening in the `OnStop` method, lets just move everything in `Cleanup` into the body of `OnStop`. Separating it out would make sense in some cases, but here it's a little redundant

2021-02-03 17:28 UTC, kolyaventuri commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +	Cleanup();
Or, I see now that you're doing the same thing in `OnTick`.. nevermind, carry on :joy:

2021-02-03 17:43 UTC, Last0xygen requested changes
I'm not really happy with this. Although it may work most of the time i see a big softlock potential here.
biggest:
* if the player switches to another player this would result in the other player not turning back to normal
* once the player dies he will be "normal" again. the effect will still be active at this point, so theres an active effect without any effect

because of that i would close this PR imho

2021-02-03 17:43 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +static std::vector<int> playerAmmo = {};
would make more sense to save them in a map than separate

2021-02-03 17:43 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +	Hash animalHash = GET_HASH_KEY(animalModels[GET_RANDOM_INT_IN_RANGE(0, static_cast<int>(animalModels.size()))]);
please use our g_random
`GET_HASH_KEY(animalModels[g_random.GetRandomInt(0, animalModels.size() - 1)])`

2021-02-03 17:43 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +	while (!STREAMING::HAS_MODEL_LOADED(animalHash)) WAIT(0);
please use brakets and new lines

2021-02-03 17:43 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +	currentModel = GET_ENTITY_MODEL(PLAYER_PED_ID());
define "PLAYER_PED_ID()" as a variable

2021-02-03 17:43 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerAnimorph.cpp
> +	}
this just keeps **some** softlocks from happening and disables the effect even after respawning (effect still running then)

2021-03-03 00:34 UTC, pongo1231 commented
Yup explicitly changing the player model is a big "no no" since it does frequently cause softlocks / crashes during missions. Will have to decline this one unfortunately.

2021-03-03 00:34 UTC, closed without merging