Added effect Spinning Cam
gta-chaos-mod/ChaosModV pull request #556
Opened 2021-02-09 16:48 UTC by ProfessorBiddle

Self explanitory, This one is a bit evil

Possible alternate name Vomit Comet

2021-02-09 21:05 UTC, Last0xygen requested changes

2021-02-09 21:05 UTC, Last0xygen commented on ChaosMod/Effects/db/Player/PlayerSpinCam.cpp
> +static Camera flippedCamera = 0;
Rename please ;P

2021-02-09 23:51 UTC, TheRealAyCe commented
Could also include the character occasionally vomiting ( https://github.com/gta-chaos-mod/ChaosModV/issues/559 ) in this effect.

2021-02-09 23:54 UTC, kolyaventuri commented
oh this is horrible.

I love it.

2021-02-10 17:53 UTC, ProfessorBiddle commented
> Could also include the character occasionally vomiting ( #559 ) in this effect.

Not sure how to do that, if someone else knows that would be amazing

2021-02-10 18:20 UTC, OHSHIET commented
Hmm I actually meant around the player, but this looks good too lol

2021-05-12 20:45 UTC, Last0xygen commented
whats that glitch at 0:18? 🤔

2021-05-12 21:03 UTC, ProfessorBiddle commented
> whats that glitch at 0:18? 🤔

not sure, probably something with the garbage ingame screen capture thing.

2021-06-02 21:45 UTC, pongo1231 commented on ConfigApp/Effects.cs
> +            {EffectType.EFFECT_PLAYER_SPIN_CAMERA, new EffectInfo("Spinning Camera", EffectCategory.PLAYER, "player_spincam", true)},
Doesn't match the effect id in the mod (`player_spinning_camera`)

2021-08-03 19:09 UTC, merged